name: Run Adzuna Ingestion

on:
  schedule:
    - cron: "0 3 * * *"   # Runs daily at 3 AM UTC
  workflow_dispatch:      # Allow manual runs

jobs:
  ingest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set env vars
        run: |
          echo "ADZUNA_APP_ID=${{ secrets.ADZUNA_APP_ID }}" >> $GITHUB_ENV
          echo "ADZUNA_APP_KEY=${{ secrets.ADZUNA_APP_KEY }}" >> $GITHUB_ENV
          echo "BUCKET_NAME=${{ secrets.BUCKET_NAME }}" >> $GITHUB_ENV
          echo "GCP_PROJECT=${{ secrets.GCP_PROJECT }}" >> $GITHUB_ENV

      - name: Run ingestion
        run: python ingest.py --pages 2 --per_page 50
